{
 "title": "i-de (Iberdrola Distribucion)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Energy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total meter consume",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iberdrola_distribucion_meter_total{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "24h energy consumed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(iberdrola_distribucion_meter_total[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "7d energy consumed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(iberdrola_distribucion_meter_total[7d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "30d energy consumed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(iberdrola_distribucion_meter_total[30d])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Max power consumption in the last 24hrs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(iberdrola_distribucion_consumption[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Consumption",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "iberdrola_distribucion_consumption{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min power consumption in the last 24hrs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(iberdrola_distribucion_consumption[24h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}