---
name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and publish the container image for ${{ github.repository }}:${{ github.ref_name }}
        uses: macbre/push-to-ghcr@v13
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: build/container/Dockerfile
          image_tag:  ${{ github.ref_name }}
      - name: Build and publish the container image for ${{ github.repository }}:latest
        uses: macbre/push-to-ghcr@v13
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: build/container/Dockerfile
          image_tag: latest
      - name: Create a Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          name: Iberdrola distribucion - Prometheus Exporter ${{ github.ref_name }}